---
# dnsmasq is used for providing split dns lookup services to bypass consul for internet dns queries.
# socat is used for forwarding docker0 requests to consul to localhost for security,
# since iptables forwarding to localhost is not well-supported especially in docker containers.
- name: install packages
  # Install latest packages
  # noqa 403
  yum:
    name:
      - dnsmasq
      - socat
      - nri-consul
    state: latest

- name: enable dnsmasq
  systemd:
    name: "dnsmasq"
    enabled: true

- name: ensure local dnsmasq is used as a DNS server
  lineinfile:
    dest: "{{ item }}"
    line: "prepend domain-name-servers 127.0.0.1;"
  with_first_found:
    - files:
      - "/etc/dhcp/dhclient.conf"
      - "/etc/dhclient.conf"
      skip: True  # skippable if not using dhcp

- include: consul.yml

# skip vault for now
#- include: vault.yml

- name: copy init files
  copy: src=etc/systemd/system/ dest=/etc/systemd/system/
