- name: copy cassandrabackups.sh
  copy:
    src: "cassandrabackups.sh"
    dest: "/opt/ivy/cassandrabackups.sh"
    mode: 0755

- name: copy cron.d definition for cassandra backups
  copy:
    src: "cassandra.cron"
    dest: "/etc/cron.d/cassandra"
    mode: 0644

- name: install java8
  yum:
    name: java-1.8.0-openjdk-headless
    state: latest

- name: remove openjdk-7
  yum:
    name: java-1.7.0-openjdk
    state: removed

- name: install apache cassandra 3.11.5
  yum:
    name:
      - https://archive.apache.org/dist/cassandra/redhat/311x/cassandra-3.11.5-1.noarch.rpm
      - https://archive.apache.org/dist/cassandra/redhat/311x/cassandra-tools-3.11.5-1.noarch.rpm
    state: latest
