---
# TODO: Not use docker

- name: checkout latest ec2metaproxy
  git:
    repo: https://github.com/nxtlytics/ec2metaproxy.git
    dest: /opt/ec2metaproxy
    accept_hostkey: yes
    version: "{{ ec2metaproxy_version }}"

- name: pull ec2metaproxy container
  docker_image:
    pull: yes
    name: "{{ ec2metaproxy_docker_image }}"

- name: save ec2metaproxy image to tar since /mnt is wiped
  command: "/usr/bin/docker save -o /root/ec2metaproxy.tar {{ ec2metaproxy_docker_image }}"

- name: copy ec2metaproxy.sh scripts
  template:
    src: opt/ivy/ec2metaproxy.sh.j2
    dest: /opt/ivy/ec2metaproxy.sh
    mode: 0755
