---
- name: add mesosphere repositories
  yum:
    name: "http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-2.noarch.rpm"

# TODO: Use newer zookeeper from somewhere other than mesosphere (3.5 has improvements!)
- name: install java, mesos, marathon, & chronos
  yum:
    name:
      - java-1.8.0-openjdk
      - mesos-1.9.0
      - marathon-1.9.109
      - chronos-2.5.1
      - mesosphere-zookeeper-3.4.6
    state: latest

- name: stop mesos services
  systemd:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - zookeeper
    - mesos-master
    - mesos-slave
    - marathon
    - chronos

- name: setup logrotation
  copy: src=etc/logrotate.d/{{ item }} dest=/etc/logrotate.d/{{ item }}
  with_items:
    - mesos
    - zookeeper
