---
- name: add mongodb repo
  yum_repository:
    name: mongodb-org-4.0
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/amazon/2/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc

- name: add pritunl repo
  yum_repository:
    name: pritunl
    description: Pritunl Repository
    baseurl: https://repo.pritunl.com/stable/yum/amazonlinux/2/
    gpgcheck: yes
