---
#### Amazon Linux Specific ####
- name: enable docker via amazon-linux-extras
  shell: "amazon-linux-extras enable docker"

- name: install docker
  yum:
    name: docker
    state: latest

- name: set docker options
  lineinfile:
    dest: "/etc/sysconfig/docker"
    regexp: "OPTIONS="
    line: 'OPTIONS="--default-ulimit nofile=262144:262144 --bip 172.17.0.1/16 --dns 172.17.0.1 -G docker --log-driver json-file --log-opt max-size=300m --log-opt max-file=3"'
