---
# Import tasks for the specific OS being built
- include: "{{ ansible_distribution }}.yml"

- name: create docker group
  group:
    name: docker

- name: add datadog agent to the docker group
  user:
    name: dd-agent
    append: yes
    groups: docker

- name: copy shell scripts
  copy:
    src: "opt/ivy/{{ item }}"
    dest: "/opt/ivy/{{ item }}"
    mode: 0755
  with_items:
    - cleanup_docker.sh

- name: enable docker cleanup
  copy:
    src: "etc/cron.daily/cleanup_docker.cron"
    dest: "/etc/cron.daily/cleanup_docker.cron"
    mode: 0755

- name: ensure docker enabled
  systemd:
    name: docker
    enabled: true

- name: install pip packages
  pip:
    name: "docker-py"
    state: latest
    extra_args: '--ignore-installed --trusted-host pypi.python.org'
